### ISSUE TITLE
Don't put plugin specific commands in the 'available commands' output

### ISSUE THREAD

**Issue by Agadar** [bart-kneepkens/DankTimesBot-Plugin-Life#10]
🥺

**Comment by bart-kneepkens** [comment]
This idea has merit. I invite you to draft a possible design for this.

**Comment by bart-kneepkens** [comment]
Done in https://github.com/bart-kneepkens/DankTimesBot-Plugin-Life/commit/94651cc252c2579c522eb4c113550ea4ee9853ea
