### ISSUE TITLE
Add /lawyer

### ISSUE THREAD

**Issue by TomChermin** [bart-kneepkens/DankTimesBot-Plugin-Life#16]
Please add a /lawyer option that functions as a /breakout, but only halves the sentence (so 16 minutes becomes 8 etc.) and has a 100% succes rate.

**Comment by TomChermin** [comment]
It should cost some points (1000 per minute or something)

**Comment by Agadar** [comment]
To be honest I'm not entirely sure if this differs enough from /breakout to justify adding it.

**Comment by Agadar** [comment]
Closing for now. Feel free to reopen or make a new issue if you think of a concrete design for /lawyer that makes it stand apart from /bribe and /breakout.
