### ISSUE TITLE
Murder + bounty

### ISSUE THREAD

**Issue by MaikoKingma** [bart-kneepkens/DankTimesBot-Plugin-Life#18]
# Concept
Add an option to murder other players and set bounties on other players. There are multiple ways to murder a players with varying success chances and requirements. A murder always requires an investment which will be calculated based on the type of murder, wallet of the murderer and wallet of the victim. This gives the idea that rich players are better guarded and thus require more investment to succesfully murder, they are also well known in the public eye and thus require more investment to commit a murder without anyone raising suspicion. (eg. rationale for game balance) 
 
On a successful murder you get the bounty(s) (if there is one) and the victim will be in the hospital for 24hours, otherwise you go to prison for 24hours. 
Users in the hospital can't do any actions, can't be murdered and any pending actions (eg. working) will be aborted.

Feel free to pick and choose which parts to implement.
 
## V1.0
/setbounty [user to set bounty on (must use @ to inform the victim)] [amount]  
  
/planmurder [snipe|stab|driveby]  

**Snipe**  
- investment 50% of the total amount of dtp of the victim + 50% of the total amount of dtp of the murderer  
- 80% success chance  
- Can't be used when in prison  
- Can be used on prisoners (success chance changed to 50%)  
- Can't have any accomplices  
- duration: 1 hour  
- 
**Stab**  
- investment will be 1000dtp per murderer/accomplice  
- 30% success chance + 2% per accomplice (max 40%)  
- When in prison can only be used on other prisoners  
- When not in prison can not be used on prisoners.  
- duration: 10min + 1min for each accomplice  
- 
**Driveby**  
- investment 20% of the total amount of dtp of the victim + 20% of the total amount of dtp of the murderer  
- 50% success chance + 2% per accomplice (max 70%)  
- Can't be used when in prison or on prisoners  
- duration: 10min + 5min for each accomplice  
  
/accomplice [murderer]  
Become an accomplice to a murder currently being planned. You will receive equal parts of the bounty if successful, go to prison if not and will pay equal parts of the investment.  
  
/executemurder  
- Investment will be payed (devided between the murderer and his accomplices)  
- Murder result will be posted in the set duration of the specified murder type and no other user has managed to murder the victim by this point.  
  
Edge cases:  
* when the victim goes to a location where he can't be murdered the investment(s) will be returned  
* when the murderer is broken out of jail before murdering another prisoner which was planned he will murder the user breaking him out instead, same success chance, if there is any bounty on the person breaking the murderer out the bounty will be payed. The bounty on the original victim is not impacted.  
  
## V2.0  
/guardvacancy [salary] [bonus in case of murder prevention] [nr of available positions]  
- Salary will be received every 24 hours  
- bonus will be payed when a murder attempt on the employer fails  
- All guards will automatically lose their job when a murder attempt on the employer succeeds  
- All guards will automatically lose their job when their employer goes to prison  
- regardless of the murder attempt outcome there is a 50% chance for each guard to die defending his employer, guard goes to hospital for 12 hours, salary and potential bonus will still be payed.  
  
/guard [user to guard]  
- User must have an open job offer/vacancy  
- When employed as a guard the user can't do any other actions (murder, guard, hustle, work)  
  
/fire [user to fire]  
- User to fire must be currently employed by the user that sends the command

**Comment by TomChermin** [comment]
A succesfull hustle should increase your bounty

**Comment by Agadar** [comment]
Initial implementation done in 68b206320496c974e09004b60280926381f8c5ee.

Hustles, breakouts, bribes, and unlawful killings all increase police bounties.
There's police bounties as mentioned, and player bounties, placed by players on players.
Killing a player earns you all bounties for that player and those bounties are cleared.
Killing a player is 60% chance and costs 25% of your and your target's worth. Failing an unlawful killing in particular lands you in jail.
A 'killed' player is stuck in the hospital for 8 hours.

**Comment by Agadar** [comment]
Should add bounties collected leaderboard to show the top dog bounty hunters.

**Comment by Agadar** [comment]
Should update /bounties so it shows player+police bounties together instead of two separate lists. Cuts printout in half and removes the mental additions you have to do to get your full bounty. Compensate by placing a police emoji or something on lines that partly contain police bounties.

**Comment by Agadar** [comment]
Closing as the initial bounty implementation was finished a while ago and no further activities were undertaken. For future potential enhancements to the bounty system, let's make new bite-sized issues.
