### ISSUE TITLE
usersNotTagged should also be adhered to when mortally wounded

### ISSUE THREAD

**Issue by coooby12** [bart-kneepkens/DankTimesBot-Plugin-Life#19]
In the current state users will still get tagged when usersNotTagged flag is set when a kill attempt succeeds.

please fix :(

https://github.com/bart-kneepkens/DankTimesBot-Plugin-Life/blob/11da293de1e1c7e9136c0cdd794449290e9223ec/plugin.ts#L220

**Comment by Agadar** [comment]
Fixed in e59d9497a11dea201981b040602d8e16fb41ed27.
