### ISSUE TITLE
Rework /work and /hustle

### ISSUE THREAD

**Issue by Agadar** [bart-kneepkens/DankTimesBot-Plugin-Life#21]
/work and especially /hustle are basically free money printing right now. We should consider a more exciting, less moneyprinting engagement with the life plugin. Any suggestions can be posted here.

**Comment by bart-kneepkens** [comment]
What does 'printing free money' mean? You could consider any plug-in that offers a points reward to be printing free money in return for player effort.

**Comment by Agadar** [comment]
Yes, we do.

Gambling plugins at least have a house edge so statistically are a net points loss for players. /work and /hustle are guaranteed and easy profit.

**Comment by Agadar** [comment]
Closing for now. If anyone ever has a concrete idea, they can submit it in a new ticket.
