### ISSUE TITLE
Nerf hustling

### ISSUE THREAD

**Issue by Agadar** [bart-kneepkens/DankTimesBot-Plugin-Life#5]
Hustle rewards are currently so high that it is very lucrative to spam the hustle action until you get jailed, and then spam it again when you're free, ad infinitum. Some suggestions:

1. Nerf the rewards
2. Add some downtime between hustles or make them take a while, like working
3. Going to jail takes away all your recent hustle money
4. Repeated offenses will increase jail time up until a point you're jailed for life or given the chair, the latter resulting in you losing all of your points

**Comment by bart-kneepkens** [comment]
In this game of life, crime pays. You risk going into prison for up to 20 minutes.
