### ISSUE TITLE
When jail/work time is less than a minute, the message shows '0 more minutes'

### ISSUE THREAD

**Issue by Agadar** [bart-kneepkens/DankTimesBot-Plugin-Life#9]
It should say something along the lines of 'x more seconds' or 'less than a minute'.

**Comment by bart-kneepkens** [comment]
Fixed in https://github.com/bart-kneepkens/DankTimesBot-Plugin-Life/commit/d6382588832d6d0da9ab31b1c0c8bfd0aac05690
